name: build-models
on: [push]
jobs:
  render-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install OpenSCAD
        run: apt-get update && apt-get install -y --no-install-recommends openscad
      
      - name: Install NPM Packages
        run: npm install

      - name: Run Build script
        run: node build.js
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: output/**
