name: build-models
on: 
  push:
    branches:
      - main

jobs:
  render-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install OpenSCAD
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends openscad
      
      - name: Install NPM Packages
        run: npm install

      - name: Run Build script
        run: node build.js
      
      - name: Generate zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r models.zip -d output

      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.create_tag.outputs.new_version }}
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          files: models.zip
